In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt # data visualization
import seaborn as sns # statistical data visualization
%matplotlib inline
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.linear_model import LogisticRegression


In [2]:
eff_df = pd.read_csv("/Users/nguyenhalinh/Desktop/Research/42101_county_dea.csv")

FileNotFoundError: [Errno 2] No such file or directory: '/Users/nguyenhalinh/Desktop/Research/42101_county_dea.csv'

In [90]:
eff_df.shape

(19975, 11)

In [92]:
19975-1823-95-48-2-1

18006

In [93]:
-1823-95-48-2-1

-1969

In [88]:
eff_df['DEA'].value_counts()

0.400000    4036
0.303030    3246
1.000000    1823
0.181818    1033
0.227273     757
0.232558     732
0.238095     709
0.243902     688
0.263158     679
0.250000     666
0.256410     650
0.270270     630
0.277778     616
0.222222     506
0.204082     475
0.166667     456
0.208333     439
0.212766     425
0.217391     417
0.400000     213
0.303030     152
0.400000     122
1.000000      95
0.227273      49
1.000000      48
0.270270      41
0.243902      41
0.250000      38
0.238095      38
0.212766      34
0.263158      34
0.277778      33
0.222222      25
0.217391      20
0.303030       2
1.000000       2
0.243902       1
0.181818       1
0.277778       1
1.000000       1
0.400000       1
Name: DEA, dtype: int64

In [33]:
eff_df = eff_df.drop(eff_df.columns[0],axis=1)

In [34]:
eff_df = eff_df.drop(eff_df.columns[5],axis=1)

In [35]:
eff_df

loan_amount  property_value  income  debt_to_income_ratio  outcome  \
0            115.0           115.0    51.0                  44.0      1.0   
1            145.0           145.0    43.0                  39.0      1.0   
2            165.0           175.0    49.0                  25.0      1.0   
3              5.0           175.0    49.0                  25.0      1.0   
4             95.0           115.0    72.0                  25.0      1.0   
...            ...             ...     ...                   ...      ...   
19970          5.0            85.0    46.0                  42.0      1.0   
19971         85.0            85.0    46.0                  43.0      1.0   
19972        525.0           555.0   227.0                  25.0      1.0   
19973        245.0           305.0   213.0                  33.0      1.0   
19974        405.0           405.0    65.0                  49.0      1.0   

       eff_loan_amount  eff_property_value  eff_income  \
0                189.0               210.0        51.0   
1                188.4               207.6        43.0   
2                188.8               209.4        49.0   
3                188.8               209.4        49.0   
4                190.6               216.1        72.0   
...                ...                 ...         ...   
19970            188.6               208.5        46.0   
19971            188.6               208.5        46.0   
19972            525.0               706.4       589.4   
19973            393.7               501.4       213.0   
19974            405.0               477.1       141.6   

       eff_debt_to_income_ratio  
0                          10.0  
1                          10.0  
2                          10.0  
3                          10.0  
4                          10.0  
...                         ...  
19970                      10.0  
19971                      10.0  
19972                      10.0  
19973                      10.0  
19974                      10.0  

[19975 rows x 9 columns]

In [36]:
original_df = eff_df[eff_df.columns[:5]]

In [37]:
original_df

loan_amount  property_value  income  debt_to_income_ratio  outcome
0            115.0           115.0    51.0                  44.0      1.0
1            145.0           145.0    43.0                  39.0      1.0
2            165.0           175.0    49.0                  25.0      1.0
3              5.0           175.0    49.0                  25.0      1.0
4             95.0           115.0    72.0                  25.0      1.0
...            ...             ...     ...                   ...      ...
19970          5.0            85.0    46.0                  42.0      1.0
19971         85.0            85.0    46.0                  43.0      1.0
19972        525.0           555.0   227.0                  25.0      1.0
19973        245.0           305.0   213.0                  33.0      1.0
19974        405.0           405.0    65.0                  49.0      1.0

[19975 rows x 5 columns]

## Model

In [38]:
X = original_df.drop(['outcome'], axis=1)

y = original_df['outcome']

In [39]:
# split X and y into training and testing sets

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.4, random_state = 0)

In [40]:
# check the shape of X_train and X_test

X_train.shape, X_test.shape

((11985, 4), (7990, 4))

In [41]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

scaledX_train = scaler.fit_transform(X_train)

scaledX_test = scaler.transform(X_test)

In [42]:
cols = X_train.columns

In [43]:
scaledX_train = pd.DataFrame(scaledX_train, columns=[cols])

In [44]:
scaledX_test = pd.DataFrame(scaledX_test, columns=[cols])

In [78]:
model = LogisticRegression(solver='liblinear', random_state=0)
model.fit(scaledX_train,y_train)
y_pred_test = model.predict(scaledX_test)
pred_proba_df = pd.DataFrame(model.predict_proba(scaledX_test))

threshold_list = [0.05,0.1,0.15,0.2,0.25,0.3,0.35,0.4,0.45,0.5,0.55,0.6,0.65,.7,.75,.8,.85,.9,.95,.99]
for i in threshold_list:
    print ('\n******** For PROB = {} ******'.format(i))
    Y_test_pred = pred_proba_df.applymap(lambda x: 1 if x>i else 0)
    test_accuracy = accuracy_score(y_test, Y_test_pred[Y_test_pred.columns[1:]])
    print('Our testing accuracy is {}'.format(test_accuracy))
    print(confusion_matrix(y_test,Y_test_pred[Y_test_pred.columns[1:]]))


******** For PROB = 0.05 ******
Our testing accuracy is 0.907133917396746
[[   0  742]
 [   0 7248]]

******** For PROB = 0.1 ******
Our testing accuracy is 0.907133917396746
[[   0  742]
 [   0 7248]]

******** For PROB = 0.15 ******
Our testing accuracy is 0.907133917396746
[[   0  742]
 [   0 7248]]

******** For PROB = 0.2 ******
Our testing accuracy is 0.907133917396746
[[   0  742]
 [   0 7248]]

******** For PROB = 0.25 ******
Our testing accuracy is 0.907133917396746
[[   0  742]
 [   0 7248]]

******** For PROB = 0.3 ******
Our testing accuracy is 0.907133917396746
[[   0  742]
 [   0 7248]]

******** For PROB = 0.35 ******
Our testing accuracy is 0.907133917396746
[[   0  742]
 [   0 7248]]

******** For PROB = 0.4 ******
Our testing accuracy is 0.907133917396746
[[   0  742]
 [   0 7248]]

******** For PROB = 0.45 ******
Our testing accuracy is 0.907133917396746
[[   0  742]
 [   0 7248]]

******** For PROB = 0.5 ******
Our testing accuracy is 0.907133917396746
[[   0  742]

In [76]:
cm = confusion_matrix(y_test, y_pred_test)

print('Confusion matrix\n\n', cm)

print('\nTrue Positives(TP) = ', cm[0,0])

print('\nTrue Negatives(TN) = ', cm[1,1])

print('\nFalse Positives(FP) = ', cm[0,1])

print('\nFalse Negatives(FN) = ', cm[1,0])

Confusion matrix

 [[   0  742]
 [   0 7248]]

True Positives(TP) =  0

True Negatives(TN) =  7248

False Positives(FP) =  742

False Negatives(FN) =  0


## New Model

In [50]:
new_df = eff_df[eff_df.columns[4:]]

In [53]:
#Rename columns
new_df.rename(
    columns={"eff_loan_amount": "loan_amount", "eff_property_value": "property_value", "eff_income": "income", "eff_debt_to_income_ratio":'debt_to_income_ratio'},
    inplace=True,)
new_df = new_df[new_df['outcome']==0]

/var/folders/vf/c31mrqv54zg80c74f5bw2__c0000gn/T/ipykernel_49524/2679644354.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df.rename(


In [54]:
new_df

outcome  loan_amount  property_value  income  debt_to_income_ratio
9          0.0        285.0           417.3   526.7                  10.0
17         0.0        335.0           477.5   539.8                  10.0
27         0.0        192.7           224.1    99.0                  10.0
51         0.0        192.4           222.9    95.0                  10.0
75         0.0        265.0           393.2   521.5                  10.0
...        ...          ...             ...     ...                   ...
19906      0.0        188.9           209.7    50.0                  10.0
19908      0.0        190.1           214.1    65.0                  10.0
19909      0.0        191.1           217.9    78.0                  10.0
19923      0.0        275.0           345.0   163.0                  10.0
19958      0.0        188.7           208.8    47.0                  10.0

[1897 rows x 5 columns]

In [55]:
newX_test = new_df.drop(['outcome'], axis=1)
newy_test = new_df['outcome']

In [56]:
new_scaledX_test = scaler.transform(newX_test)

In [57]:
new_scaledX_test = pd.DataFrame(new_scaledX_test, columns=[cols])

In [83]:
PROB = 0.75
new_y_pred_test = model.predict(new_scaledX_test)
new_pred_proba_df = pd.DataFrame(model.predict_proba(new_scaledX_test))

print ('\n******** For PROB = {} ******'.format(PROB))
new_Y_test_pred = new_pred_proba_df.applymap(lambda x: 1 if x>PROB else 0)
test_accuracy = accuracy_score(newy_test, new_Y_test_pred[new_Y_test_pred.columns[1:]])
print('Our testing accuracy is {}'.format(test_accuracy))
print(confusion_matrix(newy_test,new_Y_test_pred[new_Y_test_pred.columns[1:]]))


******** For PROB = 0.75 ******
Our testing accuracy is 0.0
[[   0 1897]
 [   0    0]]


In [84]:
cm = confusion_matrix(newy_test, new_y_pred_test)

print('Confusion matrix\n\n', cm)

print('\nTrue Positives(TP) = ', cm[0,0])

print('\nTrue Negatives(TN) = ', cm[1,1])

print('\nFalse Positives(FP) = ', cm[0,1])

print('\nFalse Negatives(FN) = ', cm[1,0])

Confusion matrix

 [[   0 1897]
 [   0    0]]

True Positives(TP) =  0

True Negatives(TN) =  0

False Positives(FP) =  1897

False Negatives(FN) =  0


In [82]:
new_pred_proba_df

0         1
0     0.017562  0.982438
1     0.016198  0.983802
2     0.022044  0.977956
3     0.022071  0.977929
4     0.018139  0.981861
...        ...       ...
1892  0.022386  0.977614
1893  0.022280  0.977720
1894  0.022189  0.977811
1895  0.019099  0.980901
1896  0.022407  0.977593

[1897 rows x 2 columns]